load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "data-utils",
    srcs = ["data_utils.cpp"],
    hdrs = ["data_utils.hpp"],
    visibility = ["//visibility:public"],
    deps = ["@eigen"],
)
